# Generated by Django 4.1.4 on 2023-02-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_user_image.webp', upload_to='user_images'),
        ),
    ]
