# Generated by Django 4.1.4 on 2023-02-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_followingtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag'),
        ),
    ]
