# Generated by Django 4.1.4 on 2023-02-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_followingtags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followingtags',
            options={'default_related_name': 'following_tags'},
        ),
    ]
